### ISSUE TITLE
Installation with --prefix failes

### ISSUE THREAD

**Issue by joede** [codebrainz/overview-plugin#18]
I've tried to build the plugin running Debian 8 Jessie. The compilation works fine, but the installation failes. I've called `configure` with a `--prefix` point inside my home path. While the documentation seems to be installed correct, make tries to install the shared library into `/usr/lib`.

I've executed the following steps:

```
$ ./autogen.sh
$ ./configure.sh --prefix /home/xxx/local
$ make
$ make install
```

A `make install --dry-run` show the following problematic section:

```
test -z "$list2" || { \
  echo " /bin/mkdir -p '/usr/lib/x86_64-linux-gnu/geany'"; \
  /bin/mkdir -p "/usr/lib/x86_64-linux-gnu/geany" || exit 1; \
  echo " /bin/bash ../libtool   --mode=install /usr/bin/install -c  $list2 '/usr/lib/x86_64-linux-gnu/geany'"; \
  /bin/bash ../libtool   --mode=install /usr/bin/install -c  $list2 "/usr/lib/x86_64-linux-gnu/geany"; \
}
```

**Comment by codebrainz** [comment]
Like "Geany-Plugins" build system, it has an option `--with-geany-libdir` you should probably use (see `configure --help`).

**Comment by joede** [comment]
Thanks for the hint. I have not recognized this option. Now the installation work. I'll have a deeper look tomorrow. ;-)
