### ISSUE TITLE
Preferences dialogue is not initialized with correct values

### ISSUE THREAD

**Issue by jolange** [codebrainz/overview-plugin#2]
Hi,
I just read about this plugin on the ML, looks really nice so far!

What I noticed so far: the boolean-like options in the dialogue are always initialized to the "first" value. E.g., the position is always set to "Left", if you open the preferences window, although the option is correctly stored in prefs.conf.
This does not seem to affect non-boolean options, because width, zoom-level and colors are handled correctly.

Cheers,
Johannes

**Comment by codebrainz** [comment]
Yeah, I know, there's a few more little things like this too. It's why I warned about it being very new and not fully debugged :)

**Comment by codebrainz** [comment]
Thanks for testing and reporting!
