### ISSUE TITLE
Option to always show entire document

### ISSUE THREAD

**Issue by romlok** [codebrainz/overview-plugin#20]
I would like the ability to always be able to see the entire document structure in the overview - no matter how many lines there are in the file.

Even with zoom set at the lower limit (-10), I have many files which do not entirely fit in the overview area, which itself then needs scrolling. I would prefer that the zoom setting be an upper limit, and for the actual zoom level (or line height?) used to be effectively dynamic based on the length of the file and available draw space.

**Comment by codebrainz** [comment]
I think it may be due to [Scintilla](http://www.scintilla.org/)'s [limits on zooming-out](http://www.scintilla.org/ScintillaDoc.html#Zooming). If I remember correctly I experimented with this and there's not much point zooming out farther as the overview contents become unusably small.

**Comment by codebrainz** [comment]
Feel free to submit a pull request though, I just won't implement it myself, if someone prove it's usable, I would merge it.
