### ISSUE TITLE
Geany crashes after installing overview plugin and then restarting

### ISSUE THREAD

**Issue by shankhs** [codebrainz/overview-plugin#6]
This bug appeared after I installed overview-plugin. The steps to reproduce is to :
1. Install overview plugin while some files are loaded
2. Restart geany-> Geany crashes
3. Open geany in -p mode and close all the geany.
4. Open geany normally -> geany opens fine

Below is the crash log:

Geany-INFO: Geany 1.25 (git >= 147167c), en_US.UTF-8
Geany-INFO: GTK 2.24.23, GLib 2.40.2
Geany-INFO: System data dir: /usr/local/share/geany
Geany-INFO: User config dir: /home/shankhs/.config/geany
Geany-INFO: System plugin path: /usr/local/lib/geany
Geany-INFO: Added filetype Genie (58).
Geany-INFO: Added filetype Graphviz (59).
Geany-INFO: Added filetype Go (60).
Geany-INFO: Added filetype Cython (61).
Geany-INFO: Added filetype Clojure (62).
Geany-INFO: Added filetype CUDA (63).
Geany-INFO: Added filetype Scala (64).
Geany-INFO: Loaded:   /usr/local/lib/geany/autoclose.so (Auto-close)
Geany-INFO: Loaded:   /usr/local/lib/geany/debugger.so (Debugger)
Geany-INFO: Loaded:   /usr/local/lib/geany/geanydoc.so (Doc)
Geany-INFO: Loaded:   /usr/local/lib/geany/geanyvc.so (GeanyVC)
Geany-INFO: Loaded:   /usr/local/lib/geany/geanynumberedbookmarks.so (Numbered Bookmarks)
Geany-INFO: Loaded:   /usr/local/lib/geany/overview.so (Overview)
Geany-INFO: Loaded:   /usr/local/lib/geany/pairtaghighlighter.so (Pair Tag Highlighter)

(geany:14834): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:2462: signal 'project-before-save' is invalid for instance '0x22b6280' of type 'GeanyObject'
Geany-INFO: Loaded:   /usr/local/lib/geany/scope.so (Scope Debugger)
Geany-INFO: Loaded:   /usr/local/lib/geany/splitwindow.so (Split Window)
Geany-INFO: Loaded:   /usr/local/lib/geany/updatechecker.so (Updatechecker)

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::browser-auto-reload after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::browser-last-uri after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::browser-orientation after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::browser-position after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::browser-separate-window-geometry after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::inspector-window-geometry after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::inspector-detached after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::wm-secondary-windows-skip-taskbar after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::wm-secondary-windows-are-transient after class was initialised

(geany:14834): GLib-GObject-WARNING **: Attempt to add property GwhSettings::wm-secondary-windows-type after class was initialised
No bp log location saved, using default.
[000:000] Cpu: 20.2.0, x2, 1400Mhz, 3544MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:001] Using Gtk2 toolkit
No bp log location saved, using default.
[000:000] Cpu: 20.2.0, x2, 1400Mhz, 3544MB
[000:000] Computer model: Not available
[000:049] No bp log location saved, using default.
[000:051] Cpu: 20.2.0, x2, 1400Mhz, 3544MB
[000:051] Computer model: Not available
[000:052] Browser XEmbed support present: 1
[000:052] Browser toolkit is Gtk2.
[000:052] Using Gtk2 toolkit
[000:049] No bp log location saved, using default.
[000:050] Cpu: 20.2.0, x2, 1400Mhz, 3544MB
[000:050] Computer model: Not available
Geany-INFO: Loaded:   /usr/local/lib/geany/webhelper.so (Web helper)
Geany-INFO: /home/shankhs/<filename>.js : Javascript (UTF-8)
Geany-INFO: /home/shankhs/<filename>.js : Javascript (UTF-8)
Geany-INFO: /home/shankhs/<filename>.js : Javascript (UTF-8)
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
Segmentation fault (core dumped)

Please do tell me if you need any more info. Love the plugin but uninstalled for now, would love to see a stable version.

**Comment by codebrainz** [comment]
The Webhelper output is suspicious (@b4n), but I'm not sure from that.

There's 2 things it might be: 1) you grabbed the code before I fixed the unload bug (4c2168048b3d73fe1ea19d78656743b51c542400) or 2) you're using the overview bar on the left-hand side of the main editor view, which is kind of experimental/not-working/crashy right now until I apply [a patch](https://github.com/codebrainz/overview-plugin/blob/e8430c5abb832ed41a308dcce566cdcf9f5aa1dc/patches/geanyscihunting.patch) to Geany's source code.

If it's neither of those, then it would be useful to get a GDB traceback, if you don't mind.

**Comment by shankhs** [comment]
I pulled the latest version and changed the preferences to display right and that fixed the issue.

Thanks :)

**Comment by codebrainz** [comment]
Cool, thanks for testing again.

BTW, if you really want the RTL layout, you can apply the patch in `patches` directory to a checkout of Geany from Git, or pull from this PR:

https://github.com/geany/geany/pull/442

At least until it's merged. It should hopefully be in the next Geany release.
